services:
  db:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: nexdom-db
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: Oracle_1234
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "lsnrctl", "status"]
      interval: 30s
      retries: 10

  nexdom:
    build: .
    container_name: nexdom-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 1521
      DB_SID: ORCLCDB
      DB_SERVICE: ORCLPDB1
      DB_USER: system
      DB_PASSWORD: Oracle_1234
    ports:
      - "8080:8080"
    networks:
      - nexdom-net

volumes:
  oracle-data:

networks:
  nexdom-net: