services:
  db:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: vortex-db
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: Oracle_1234
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ../oracle/init:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "lsnrctl", "status"]
      interval: 30s
      retries: 10
    networks:
      - vortex-net

  vortex:
    build: 
      context: ../..
      dockerfile: infra/docker/Dockerfile.backend
    container_name: vortex-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "prd,kafka"
      DB_HOST: db
      DB_PORT: 1521
      DB_SID: ORCLCDB
      DB_SERVICE: ORCLPDB1
      DB_USER: system
      DB_PASSWORD: Oracle_1234
      # Configurações Kafka para Docker
      KAFKA_ENABLED: "true"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      SPRING_KAFKA_CONSUMER_GROUP_ID: "vortex-inventory-group"
    ports:
      - "8080:8080"
    networks:
      - vortex-net
      - vortex-simple
    external_links:
      - vortex-kafka-simple:kafka
      - vortex-zookeeper-simple:zookeeper

volumes:
  oracle-data:

networks:
  vortex-net:
  vortex-simple:
    external: true